/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t bmw.glb 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'EmptyAction' | 'EmptyAction.001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
    Plane005_2: THREE.Mesh
    Plane005_3: THREE.Mesh
    Plane005_4: THREE.Mesh
    Plane005_5: THREE.Mesh
    Plane005_6: THREE.Mesh
    Plane012: THREE.Mesh
    Plane012_1: THREE.Mesh
    Plane012_2: THREE.Mesh
    Plane012_3: THREE.Mesh
    Plane012_4: THREE.Mesh
    Plane012_5: THREE.Mesh
    Plane012_6: THREE.Mesh
    Plane017: THREE.Mesh
    Plane017_1: THREE.Mesh
    Plane017_2: THREE.Mesh
    Plane017_3: THREE.Mesh
    Plane017_4: THREE.Mesh
    Plane017_5: THREE.Mesh
    Plane017_6: THREE.Mesh
    Plane018: THREE.Mesh
    Plane018_1: THREE.Mesh
    Plane018_2: THREE.Mesh
    Plane018_3: THREE.Mesh
    Plane018_4: THREE.Mesh
    Plane018_5: THREE.Mesh
    Plane018_6: THREE.Mesh
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    Plane004_3: THREE.Mesh
    Plane004_4: THREE.Mesh
    Plane004_5: THREE.Mesh
    Plane004_6: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane003_2: THREE.Mesh
    Plane003_3: THREE.Mesh
    Plane003_4: THREE.Mesh
    Plane003_5: THREE.Mesh
    Plane003_6: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
    Plane002_3: THREE.Mesh
    Plane002_4: THREE.Mesh
    Plane002_5: THREE.Mesh
    Plane002_6: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
    Plane001_3: THREE.Mesh
    Plane001_4: THREE.Mesh
    Plane001_5: THREE.Mesh
    Plane001_6: THREE.Mesh
    Text001: THREE.Mesh
    Desirefx_me_body016: THREE.Mesh
    Desirefx_me_body016_1: THREE.Mesh
    Desirefx_me_body016_2: THREE.Mesh
    Desirefx_me_body016_3: THREE.Mesh
    Desirefx_me_body016_4: THREE.Mesh
    Desirefx_me_body016_5: THREE.Mesh
    Desirefx_me_body016_6: THREE.Mesh
    Desirefx_me_body016_7: THREE.Mesh
    Desirefx_me_body016_8: THREE.Mesh
    Desirefx_me_body016_9: THREE.Mesh
    Desirefx_me_body016_10: THREE.Mesh
    Desirefx_me_body016_11: THREE.Mesh
    Desirefx_me_body016_12: THREE.Mesh
    Desirefx_me_body016_13: THREE.Mesh
    Desirefx_me_body016_14: THREE.Mesh
    Desirefx_me_body016_15: THREE.Mesh
    Desirefx_me_body016_16: THREE.Mesh
    Desirefx_me_body016_17: THREE.Mesh
    Desirefx_me_body016_18: THREE.Mesh
    Text002: THREE.Mesh
    Desirefx_me_body001: THREE.Mesh
    Desirefx_me_body001_1: THREE.Mesh
    Desirefx_me_body001_2: THREE.Mesh
    Desirefx_me_body001_3: THREE.Mesh
    Desirefx_me_body001_4: THREE.Mesh
    Desirefx_me_body001_5: THREE.Mesh
    Desirefx_me_body001_6: THREE.Mesh
    Desirefx_me_body001_7: THREE.Mesh
    Desirefx_me_body001_8: THREE.Mesh
    Desirefx_me_body001_9: THREE.Mesh
    Desirefx_me_body001_10: THREE.Mesh
    Desirefx_me_body001_11: THREE.Mesh
    Desirefx_me_body001_12: THREE.Mesh
    Desirefx_me_body001_13: THREE.Mesh
    Desirefx_me_body001_14: THREE.Mesh
    Desirefx_me_body001_15: THREE.Mesh
    Desirefx_me_body001_16: THREE.Mesh
    Desirefx_me_body001_17: THREE.Mesh
    Desirefx_me_body001_18: THREE.Mesh
  }
  materials: {
    ['Front Tire']: THREE.MeshStandardMaterial
    ['Front Tire.001']: THREE.MeshStandardMaterial
    ['glossy black']: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    ['brake.001']: THREE.MeshStandardMaterial
    mat: THREE.MeshStandardMaterial
    brake: THREE.MeshStandardMaterial
    ['Front Tire.002']: THREE.MeshStandardMaterial
    ['Front Tire.003']: THREE.MeshStandardMaterial
    ['glossy black.003']: THREE.MeshStandardMaterial
    ['chrome.001']: THREE.MeshStandardMaterial
    ['brake.002']: THREE.MeshStandardMaterial
    ['mat.001']: THREE.MeshStandardMaterial
    ['brake.003']: THREE.MeshStandardMaterial
    ['glossy black.002']: THREE.MeshPhysicalMaterial
    body: THREE.MeshStandardMaterial
    ['headlight glass']: THREE.MeshStandardMaterial
    ['Mat mt']: THREE.MeshStandardMaterial
    windows: THREE.MeshStandardMaterial
    ['spoiler ']: THREE.MeshStandardMaterial
    ['spoiler .001']: THREE.MeshStandardMaterial
    ['headlight.002']: THREE.MeshPhysicalMaterial
    ['glossy black.001']: THREE.MeshStandardMaterial
    mirror: THREE.MeshPhysicalMaterial
    ['headlight.001']: THREE.MeshStandardMaterial
    ['glass.001']: THREE.MeshPhysicalMaterial
    ['Mat mt.002']: THREE.MeshStandardMaterial
    ['Mat mt.001']: THREE.MeshStandardMaterial
    ['back headlight']: THREE.MeshStandardMaterial
    ['white.007']: THREE.MeshStandardMaterial
    ['glossy black.004']: THREE.MeshPhysicalMaterial
    ['Mat mt.003']: THREE.MeshStandardMaterial
    ['back healight']: THREE.MeshPhysicalMaterial
    ['glossy black.005']: THREE.MeshPhysicalMaterial
    ['body.001']: THREE.MeshStandardMaterial
    ['headlight glass.001']: THREE.MeshStandardMaterial
    ['Mat mt.004']: THREE.MeshStandardMaterial
    ['windows.001']: THREE.MeshStandardMaterial
    ['spoiler .002']: THREE.MeshStandardMaterial
    ['spoiler .003']: THREE.MeshStandardMaterial
    ['headlight.003']: THREE.MeshPhysicalMaterial
    ['glossy black.006']: THREE.MeshStandardMaterial
    ['mirror.001']: THREE.MeshPhysicalMaterial
    ['headlight.004']: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshPhysicalMaterial
    ['Mat mt.005']: THREE.MeshStandardMaterial
    ['Mat mt.006']: THREE.MeshStandardMaterial
    ['back headlight.001']: THREE.MeshStandardMaterial
    ['white.001']: THREE.MeshStandardMaterial
    ['glossy black.007']: THREE.MeshPhysicalMaterial
    ['Mat mt.007']: THREE.MeshStandardMaterial
    ['back healight.001']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}
// @ts-ignore
export function Mercedes(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const group = React.useRef<THREE.Group>() // @ts-ignore
  const { nodes, materials, animations } = useGLTF('/bmw.glb') as GLTFResult 
  // @ts-ignore
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 1.106, -0.623]}>
          <group name="tyre_BL" position={[0.426, -0.918, -0.576]} rotation={[-0.623, 0, 0]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Front Tire']} />
            <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials['Front Tire.001']} />
            <mesh name="Plane005_2" geometry={nodes.Plane005_2.geometry} material={materials['glossy black']} />
            <mesh name="Plane005_3" geometry={nodes.Plane005_3.geometry} material={materials.chrome} />
            <mesh name="Plane005_4" geometry={nodes.Plane005_4.geometry} material={materials['brake.001']} />
            <mesh name="Plane005_5" geometry={nodes.Plane005_5.geometry} material={materials.mat} />
            <mesh name="Plane005_6" geometry={nodes.Plane005_6.geometry} material={materials.brake} />
          </group>
          <group name="tyre_BR" position={[-0.423, -0.918, -0.576]} rotation={[-2.518, 0, -Math.PI]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Front Tire']} />
            <mesh name="Plane012_1" geometry={nodes.Plane012_1.geometry} material={materials['Front Tire.001']} />
            <mesh name="Plane012_2" geometry={nodes.Plane012_2.geometry} material={materials['glossy black']} />
            <mesh name="Plane012_3" geometry={nodes.Plane012_3.geometry} material={materials.chrome} />
            <mesh name="Plane012_4" geometry={nodes.Plane012_4.geometry} material={materials['brake.001']} />
            <mesh name="Plane012_5" geometry={nodes.Plane012_5.geometry} material={materials.mat} />
            <mesh name="Plane012_6" geometry={nodes.Plane012_6.geometry} material={materials.brake} />
          </group>
          <group name="tyre_FL" position={[0.426, -0.918, 0.972]} rotation={[-0.623, 0, 0]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Front Tire']} />
            <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Front Tire.001']} />
            <mesh name="Plane017_2" geometry={nodes.Plane017_2.geometry} material={materials['glossy black']} />
            <mesh name="Plane017_3" geometry={nodes.Plane017_3.geometry} material={materials.chrome} />
            <mesh name="Plane017_4" geometry={nodes.Plane017_4.geometry} material={materials['brake.001']} />
            <mesh name="Plane017_5" geometry={nodes.Plane017_5.geometry} material={materials.mat} />
            <mesh name="Plane017_6" geometry={nodes.Plane017_6.geometry} material={materials.brake} />
          </group>
          <group name="tyre_FR" position={[-0.423, -0.918, 0.972]} rotation={[-2.518, 0, -Math.PI]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Front Tire']} />
            <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Front Tire.001']} />
            <mesh name="Plane018_2" geometry={nodes.Plane018_2.geometry} material={materials['glossy black']} />
            <mesh name="Plane018_3" geometry={nodes.Plane018_3.geometry} material={materials.chrome} />
            <mesh name="Plane018_4" geometry={nodes.Plane018_4.geometry} material={materials['brake.001']} />
            <mesh name="Plane018_5" geometry={nodes.Plane018_5.geometry} material={materials.mat} />
            <mesh name="Plane018_6" geometry={nodes.Plane018_6.geometry} material={materials.brake} />
          </group>
        </group>
        <group name="Empty001" position={[0, 1.106, -0.623]}>
          <group name="tyre_BL001" position={[0.426, -0.918, -0.576]} rotation={[-0.623, 0, 0]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Front Tire.002']} />
            <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['Front Tire.003']} />
            <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials['glossy black.003']} />
            <mesh name="Plane004_3" geometry={nodes.Plane004_3.geometry} material={materials['chrome.001']} />
            <mesh name="Plane004_4" geometry={nodes.Plane004_4.geometry} material={materials['brake.002']} />
            <mesh name="Plane004_5" geometry={nodes.Plane004_5.geometry} material={materials['mat.001']} />
            <mesh name="Plane004_6" geometry={nodes.Plane004_6.geometry} material={materials['brake.003']} />
          </group>
          <group name="tyre_BR001" position={[-0.423, -0.918, -0.576]} rotation={[-2.518, 0, -Math.PI]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Front Tire.002']} />
            <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Front Tire.003']} />
            <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['glossy black.003']} />
            <mesh name="Plane003_3" geometry={nodes.Plane003_3.geometry} material={materials['chrome.001']} />
            <mesh name="Plane003_4" geometry={nodes.Plane003_4.geometry} material={materials['brake.002']} />
            <mesh name="Plane003_5" geometry={nodes.Plane003_5.geometry} material={materials['mat.001']} />
            <mesh name="Plane003_6" geometry={nodes.Plane003_6.geometry} material={materials['brake.003']} />
          </group>
          <group name="tyre_FL001" position={[0.426, -0.918, 0.972]} rotation={[-0.623, 0, 0]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Front Tire.002']} />
            <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Front Tire.003']} />
            <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials['glossy black.003']} />
            <mesh name="Plane002_3" geometry={nodes.Plane002_3.geometry} material={materials['chrome.001']} />
            <mesh name="Plane002_4" geometry={nodes.Plane002_4.geometry} material={materials['brake.002']} />
            <mesh name="Plane002_5" geometry={nodes.Plane002_5.geometry} material={materials['mat.001']} />
            <mesh name="Plane002_6" geometry={nodes.Plane002_6.geometry} material={materials['brake.003']} />
          </group>
          <group name="tyre_FR001" position={[-0.423, -0.918, 0.972]} rotation={[-2.518, 0, -Math.PI]} scale={[0.406, 0.434, 0.434]}>
            <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Front Tire.002']} />
            <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Front Tire.003']} />
            <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials['glossy black.003']} />
            <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials['chrome.001']} />
            <mesh name="Plane001_4" geometry={nodes.Plane001_4.geometry} material={materials['brake.002']} />
            <mesh name="Plane001_5" geometry={nodes.Plane001_5.geometry} material={materials['mat.001']} />
            <mesh name="Plane001_6" geometry={nodes.Plane001_6.geometry} material={materials['brake.003']} />
          </group>
        </group>
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['glossy black.002']} position={[0, 0.3, -1.336]} rotation={[1.78, 0, Math.PI]} scale={0.049} />
        <group name="roof" position={[0, 0.551, -0.623]} scale={0.001}>
          <mesh name="Desirefx_me_body016" geometry={nodes.Desirefx_me_body016.geometry} material={materials.body} />
          <mesh name="Desirefx_me_body016_1" geometry={nodes.Desirefx_me_body016_1.geometry} material={materials.chrome} />
          <mesh name="Desirefx_me_body016_2" geometry={nodes.Desirefx_me_body016_2.geometry} material={materials['headlight glass']} />
          <mesh name="Desirefx_me_body016_3" geometry={nodes.Desirefx_me_body016_3.geometry} material={materials['Mat mt']} />
          <mesh name="Desirefx_me_body016_4" geometry={nodes.Desirefx_me_body016_4.geometry} material={materials.windows} />
          <mesh name="Desirefx_me_body016_5" geometry={nodes.Desirefx_me_body016_5.geometry} material={materials['spoiler ']} />
          <mesh name="Desirefx_me_body016_6" geometry={nodes.Desirefx_me_body016_6.geometry} material={materials['spoiler .001']} />
          <mesh name="Desirefx_me_body016_7" geometry={nodes.Desirefx_me_body016_7.geometry} material={materials['headlight.002']} />
          <mesh name="Desirefx_me_body016_8" geometry={nodes.Desirefx_me_body016_8.geometry} material={materials['glossy black.001']} />
          <mesh name="Desirefx_me_body016_9" geometry={nodes.Desirefx_me_body016_9.geometry} material={materials.mirror} />
          <mesh name="Desirefx_me_body016_10" geometry={nodes.Desirefx_me_body016_10.geometry} material={materials['headlight.001']} />
          <mesh name="Desirefx_me_body016_11" geometry={nodes.Desirefx_me_body016_11.geometry} material={materials['glass.001']} />
          <mesh name="Desirefx_me_body016_12" geometry={nodes.Desirefx_me_body016_12.geometry} material={materials['Mat mt.002']} />
          <mesh name="Desirefx_me_body016_13" geometry={nodes.Desirefx_me_body016_13.geometry} material={materials['Mat mt.001']} />
          <mesh name="Desirefx_me_body016_14" geometry={nodes.Desirefx_me_body016_14.geometry} material={materials['back headlight']} />
          <mesh name="Desirefx_me_body016_15" geometry={nodes.Desirefx_me_body016_15.geometry} material={materials['white.007']} />
          <mesh name="Desirefx_me_body016_16" geometry={nodes.Desirefx_me_body016_16.geometry} material={materials['glossy black.004']} />
          <mesh name="Desirefx_me_body016_17" geometry={nodes.Desirefx_me_body016_17.geometry} material={materials['Mat mt.003']} />
          <mesh name="Desirefx_me_body016_18" geometry={nodes.Desirefx_me_body016_18.geometry} material={materials['back healight']} />
        </group>
        <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials['glossy black.005']} position={[0, 0.3, -1.336]} rotation={[1.78, 0, Math.PI]} scale={0.049} />
        <group name="roof001" position={[0, 0.551, -0.623]} scale={0.001}>
          <mesh name="Desirefx_me_body001" geometry={nodes.Desirefx_me_body001.geometry} material={materials['body.001']} />
          <mesh name="Desirefx_me_body001_1" geometry={nodes.Desirefx_me_body001_1.geometry} material={materials['chrome.001']} />
          <mesh name="Desirefx_me_body001_2" geometry={nodes.Desirefx_me_body001_2.geometry} material={materials['headlight glass.001']} />
          <mesh name="Desirefx_me_body001_3" geometry={nodes.Desirefx_me_body001_3.geometry} material={materials['Mat mt.004']} />
          <mesh name="Desirefx_me_body001_4" geometry={nodes.Desirefx_me_body001_4.geometry} material={materials['windows.001']} />
          <mesh name="Desirefx_me_body001_5" geometry={nodes.Desirefx_me_body001_5.geometry} material={materials['spoiler .002']} />
          <mesh name="Desirefx_me_body001_6" geometry={nodes.Desirefx_me_body001_6.geometry} material={materials['spoiler .003']} />
          <mesh name="Desirefx_me_body001_7" geometry={nodes.Desirefx_me_body001_7.geometry} material={materials['headlight.003']} />
          <mesh name="Desirefx_me_body001_8" geometry={nodes.Desirefx_me_body001_8.geometry} material={materials['glossy black.006']} />
          <mesh name="Desirefx_me_body001_9" geometry={nodes.Desirefx_me_body001_9.geometry} material={materials['mirror.001']} />
          <mesh name="Desirefx_me_body001_10" geometry={nodes.Desirefx_me_body001_10.geometry} material={materials['headlight.004']} />
          <mesh name="Desirefx_me_body001_11" geometry={nodes.Desirefx_me_body001_11.geometry} material={materials['glass.002']} />
          <mesh name="Desirefx_me_body001_12" geometry={nodes.Desirefx_me_body001_12.geometry} material={materials['Mat mt.005']} />
          <mesh name="Desirefx_me_body001_13" geometry={nodes.Desirefx_me_body001_13.geometry} material={materials['Mat mt.006']} />
          <mesh name="Desirefx_me_body001_14" geometry={nodes.Desirefx_me_body001_14.geometry} material={materials['back headlight.001']} />
          <mesh name="Desirefx_me_body001_15" geometry={nodes.Desirefx_me_body001_15.geometry} material={materials['white.001']} />
          <mesh name="Desirefx_me_body001_16" geometry={nodes.Desirefx_me_body001_16.geometry} material={materials['glossy black.007']} />
          <mesh name="Desirefx_me_body001_17" geometry={nodes.Desirefx_me_body001_17.geometry} material={materials['Mat mt.007']} />
          <mesh name="Desirefx_me_body001_18" geometry={nodes.Desirefx_me_body001_18.geometry} material={materials['back healight.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bmw.glb')
