/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public\boeing.glb 
Author: Muhamad Mirza Arrafi (https://sketchfab.com/nazidefenseforceofficial)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-ch-47-chinook-military-transport-aircraft-cdac73e931f6482e86960a326fef73bf
Title: Boeing CH-47 Chinook Military Transport Aircraft
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    ['13___Default']: THREE.MeshStandardMaterial
    Material__14524: THREE.MeshStandardMaterial
    Material__14525: THREE.MeshStandardMaterial
    Material__14526: THREE.MeshStandardMaterial
    Material__14528: THREE.MeshStandardMaterial
    Material__14529: THREE.MeshStandardMaterial
    Material__14530: THREE.MeshStandardMaterial
    Material__14531: THREE.MeshStandardMaterial
  }
    //@ts-ignore

  animations: GLTFAction[]
}

  //@ts-ignore

export function Boeing(props: JSX.IntrinsicElements['group']) {
    //@ts-ignore

  const { nodes, materials } = useGLTF('/boeing.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['13___Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material__14524} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material__14525} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material__14526} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material__14528} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material__14529} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Material__14530} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Material__14531} />
      </group>
    </group>
  )
}

useGLTF.preload('/boeing.glb')
