/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public\guitar.glb 
Author: abazibiz (https://sketchfab.com/abazibiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ibanez-jem-guitar-daeadd913644438aa3096bb357a02016
Title: ibanez jem guitar
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    lambert4SG: THREE.MeshStandardMaterial
    lambert5SG: THREE.MeshStandardMaterial
  }
    //@ts-ignore

  animations: GLTFAction[]
}
  //@ts-ignore

export function Guitar(props: JSX.IntrinsicElements['group']) {
    //@ts-ignore

  const { nodes, materials } = useGLTF('/guitar.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.094}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/guitar.glb')
