/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public\gun.glb 
Author: NksXxX (https://sketchfab.com/NksXxX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gun-307770424e1044229b8ac455cd31fcd1
Title: GUN
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
    defaultMaterial_7: THREE.Mesh
    defaultMaterial_8: THREE.Mesh
    defaultMaterial_9: THREE.Mesh
    defaultMaterial_10: THREE.Mesh
    defaultMaterial_11: THREE.Mesh
    defaultMaterial_12: THREE.Mesh
    defaultMaterial_13: THREE.Mesh
    defaultMaterial_14: THREE.Mesh
    defaultMaterial_15: THREE.Mesh
    defaultMaterial_16: THREE.Mesh
    defaultMaterial_17: THREE.Mesh
    defaultMaterial_18: THREE.Mesh
    defaultMaterial_19: THREE.Mesh
    defaultMaterial_20: THREE.Mesh
    defaultMaterial_21: THREE.Mesh
    defaultMaterial_22: THREE.Mesh
    defaultMaterial_23: THREE.Mesh
    defaultMaterial_24: THREE.Mesh
    defaultMaterial_25: THREE.Mesh
    defaultMaterial_26: THREE.Mesh
    defaultMaterial_27: THREE.Mesh
    defaultMaterial_28: THREE.Mesh
    defaultMaterial_29: THREE.Mesh
  }
  materials: {
    ['1001']: THREE.MeshStandardMaterial
    ['1011']: THREE.MeshStandardMaterial
  }
    //@ts-ignore

  animations: GLTFAction[]
}
  //@ts-ignore

export function Gun(props: JSX.IntrinsicElements['group']) {
    //@ts-ignore

  const { nodes, materials } = useGLTF('/gun.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['1001']} position={[-1.81, 0.563, 0]} rotation={[0, 0, Math.PI / 2]} scale={0.178} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['1001']} position={[1.975, 0.246, 0]} scale={[0.615, 0.751, 0.218]} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['1001']} position={[0.312, 0.476, 0]} scale={0.372} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials['1001']} position={[0.172, 0.6, 0.137]} scale={0.092} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials['1001']} position={[-0.077, 0.543, 0.141]} rotation={[Math.PI / 2, 0, 0]} scale={0.037} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials['1001']} position={[-0.04, 0.608, 0]} scale={[0.189, 0.094, 0.042]} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials['1001']} position={[-1.062, 0.142, 0]} scale={[0.545, 0.545, 0.254]} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials['1001']} position={[-0.548, 0.123, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.173, 0.136, 0.173]} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials['1001']} position={[-1.079, 0.561, 0]} scale={[0.925, 0.452, 0.452]} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials['1001']} position={[0.493, 0.484, 0.097]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.131, 0.02, 0.131]} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials['1001']} position={[-0.219, 0.307, 0.132]} rotation={[Math.PI / 2, 0, 0]} scale={[0.048, 0.008, 0.048]} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials['1001']} position={[-0.12, 0.331, 0.137]} rotation={[Math.PI / 2, 0, 0]} scale={[0.049, 0.009, 0.049]} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials['1001']} position={[-0.584, 0.152, 0]} rotation={[1.596, 0.282, 0.13]} scale={[0.128, 0.101, 0.128]} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials['1001']} position={[-0.69, -0.157, 0]} rotation={[1.533, 0.667, 0.159]} scale={[0.128, 0.101, 0.128]} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials['1001']} position={[0.326, 0.164, -0.007]} rotation={[1.608, -0.273, -3.12]} scale={[0.143, 0.107, 0.15]} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials['1001']} position={[-0.86, 0.377, 0.133]} rotation={[Math.PI / 2, -0.305, 0]} scale={[0.035, 0.008, 0.035]} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials['1001']} position={[0.634, 0.485, 0.126]} rotation={[Math.PI / 2, 0.574, 0]} scale={[0.046, 0.01, 0.046]} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials['1001']} position={[-1.329, -0.225, 0.371]} rotation={[Math.PI / 2, 0.261, 0]} scale={[0.052, 0.024, 0.052]} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials['1001']} position={[-1.329, 0.124, 0.299]} rotation={[Math.PI / 2, -0.931, 0]} scale={[0.046, 0.021, 0.046]} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials['1001']} position={[0.229, -0.512, 0]} rotation={[0, 0, 0.231]} scale={[0.362, 0.129, 0.248]} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials['1001']} position={[0.217, -0.41, 0.172]} rotation={[1.521, -0.79, 0]} scale={[0.053, 0.007, 0.053]} />
          <group position={[-1.266, 0.339, 0.174]} rotation={[0, 0, Math.PI / 2]} scale={[0.134, 0.194, 0.134]}>
            <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials['1001']} />
            <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials['1001']} />
          </group>
          <group position={[-1.266, 0.339, 0.174]} rotation={[0, 0, Math.PI / 2]} scale={[0.134, 0.194, 0.134]}>
            <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials['1001']} />
            <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials['1001']} />
          </group>
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials['1001']} position={[-0.206, 0.564, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.166, 0.058, 0.166]} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials['1001']} position={[-1.113, -0.146, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.434, 0.341, 0.434]} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials['1011']} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials['1001']} scale={[1, 1, 0.979]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gun.glb')
