/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src\assets\models\iphone_12_pro.glb -t 
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-12-pro-05dfc991665e45c68c8b7062136c0c6e
Title: iPhone 12 Pro
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Camera1_PacificBlue_0: THREE.Mesh
    Camera1_GrayGlossy_0: THREE.Mesh
    Camera1_FrontCamera_0: THREE.Mesh
    Camera1_Blackmatte_0: THREE.Mesh
    Camera1_Cameralens_0: THREE.Mesh
    Camera1_Glass_0: THREE.Mesh
    Flash_Flash2_0: THREE.Mesh
    Flash_Flash_0: THREE.Mesh
    LiDar_LiDar__0: THREE.Mesh
    FrontCamera_Cameralens_0: THREE.Mesh
    FrontCamera_FrontCamera_0: THREE.Mesh
    FrontCamera_Glass_0: THREE.Mesh
    FrontMic_GrayGlossy2_0: THREE.Mesh
    FrontMic_MicrophoneSpeaker_0: THREE.Mesh
    FrontCamera001_bezel001_0: THREE.Mesh
    Bezel_bezel_0: THREE.Mesh
    Camera3_PacificBlue_0: THREE.Mesh
    Camera3_GrayGlossy_0: THREE.Mesh
    Camera3_FrontCamera_0: THREE.Mesh
    Camera3_Blackmatte_0: THREE.Mesh
    Camera3_Cameralens_0: THREE.Mesh
    Camera3_Glass_0: THREE.Mesh
    Camera2_PacificBlue_0: THREE.Mesh
    Camera2_GrayGlossy_0: THREE.Mesh
    Camera2_FrontCamera_0: THREE.Mesh
    Camera2_Blackmatte_0: THREE.Mesh
    Camera2_Cameralens_0: THREE.Mesh
    Camera2_Glass_0: THREE.Mesh
    Screen_Wallpaper_0: THREE.Mesh
    Apple_Logo_Logo_0: THREE.Mesh
    CameraModule001_Glass_0: THREE.Mesh
    CameraModule002_MicrophoneSpeaker_0: THREE.Mesh
    iPhone12_Pro_Body_0: THREE.Mesh
    VolumeButton_BodyFrame_0: THREE.Mesh
    PowerButton_BodyFrame_0: THREE.Mesh
    Port_Blackmatte_0: THREE.Mesh
    Port_BodyFrame_0: THREE.Mesh
    SimTray_Blackmatte_0: THREE.Mesh
    SimTray_BodyFrame_0: THREE.Mesh
    MuteButton_BodyFrame_0: THREE.Mesh
    iPhone__12_Pro_BodyFrame_0: THREE.Mesh
    iPhone__12_Pro_MicrophoneSpeaker_0: THREE.Mesh
    iPhone__12_Pro_GrayGlossy2_0: THREE.Mesh
    iPhone__12_Pro_Antenna_0: THREE.Mesh
  }
  materials: {
    PacificBlue: THREE.MeshStandardMaterial
    GrayGlossy: THREE.MeshStandardMaterial
    FrontCamera: THREE.MeshStandardMaterial
    Blackmatte: THREE.MeshStandardMaterial
    Cameralens: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Flash2: THREE.MeshStandardMaterial
    Flash: THREE.MeshStandardMaterial
    LiDar: THREE.MeshStandardMaterial
    GrayGlossy2: THREE.MeshStandardMaterial
    MicrophoneSpeaker: THREE.MeshStandardMaterial
    ['bezel.001']: THREE.MeshStandardMaterial
    bezel: THREE.MeshStandardMaterial
    Wallpaper: THREE.MeshStandardMaterial
    Logo: THREE.MeshStandardMaterial
    Body: THREE.MeshStandardMaterial
    BodyFrame: THREE.MeshStandardMaterial
    Antenna: THREE.MeshStandardMaterial
  }
  // @ts-ignore
  animations: GLTFAction[]
}

// @ts-ignore
export function Model(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/iphone_12_pro.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2.588, 2.419]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.iPhone__12_Pro_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.iPhone__12_Pro_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
            <mesh geometry={nodes.iPhone__12_Pro_GrayGlossy2_0.geometry} material={materials.GrayGlossy2} />
            <mesh geometry={nodes.iPhone__12_Pro_Antenna_0.geometry} material={materials.Antenna} />
            <mesh geometry={nodes.iPhone12_Pro_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Camera1_PacificBlue_0.geometry} material={materials.PacificBlue} />
            <mesh geometry={nodes.Camera1_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
            <mesh geometry={nodes.Camera1_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.Camera1_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Camera1_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.Camera1_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Flash_Flash2_0.geometry} material={materials.Flash2} />
            <mesh geometry={nodes.Flash_Flash_0.geometry} material={materials.Flash} />
            <mesh geometry={nodes.LiDar_LiDar__0.geometry} material={materials.LiDar} />
            <mesh geometry={nodes.Bezel_bezel_0.geometry} material={materials.bezel} />
            <mesh geometry={nodes.FrontCamera_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.FrontCamera_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.FrontCamera_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.FrontMic_GrayGlossy2_0.geometry} material={materials.GrayGlossy2} />
            <mesh geometry={nodes.FrontMic_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
            <mesh geometry={nodes.FrontCamera001_bezel001_0.geometry} material={materials['bezel.001']} position={[0, 0, -0.001]} />
            <mesh geometry={nodes.Camera3_PacificBlue_0.geometry} material={materials.PacificBlue} />
            <mesh geometry={nodes.Camera3_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
            <mesh geometry={nodes.Camera3_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.Camera3_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Camera3_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.Camera3_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Camera2_PacificBlue_0.geometry} material={materials.PacificBlue} />
            <mesh geometry={nodes.Camera2_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
            <mesh geometry={nodes.Camera2_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.Camera2_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Camera2_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.Camera2_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Screen_Wallpaper_0.geometry} material={materials.Wallpaper} />
            <mesh geometry={nodes.Apple_Logo_Logo_0.geometry} material={materials.Logo} />
            <mesh geometry={nodes.CameraModule001_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.CameraModule002_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
            <mesh geometry={nodes.VolumeButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.PowerButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.Port_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Port_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.SimTray_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.SimTray_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.MuteButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone_12_pro.glb')
