/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public\jordan.glb 
Author: makoto (https://sketchfab.com/lu87813)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/air-jordan-1-a4b434181fbb48008ad460722fd53725
Title: Air Jordan 1
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    shoe_shoe_0: THREE.Mesh
    shoelace_shoelace_0: THREE.Mesh
  }
  materials: {
    shoe: THREE.MeshStandardMaterial
    shoelace: THREE.MeshStandardMaterial
  }
    //@ts-ignore

  animations: GLTFAction[]
}
  //@ts-ignore

export function Jordan(props: JSX.IntrinsicElements['group']) {
    //@ts-ignore

  const { nodes, materials } = useGLTF('/jordan.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shoe_shoe_0.geometry} material={materials.shoe} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.shoelace_shoelace_0.geometry} material={materials.shoelace} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/jordan.glb')
