/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public\kitkat.glb 
Author: Qlone (https://sketchfab.com/Qlone)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/kitkat-chunky-salted-caramel-095f0c37415749b98522d6c8ad12d686
Title: KitKat Chunky Salted Caramel
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    material0: THREE.MeshBasicMaterial
  }
    //@ts-ignore

  animations: GLTFAction[]
}
  //@ts-ignore

export function KitKat(props: JSX.IntrinsicElements['group']) {
    //@ts-ignore

  const { nodes, materials } = useGLTF('/kitkat.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material0} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitkat.glb')
