/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t retro__bike.glb 
Author: annzep (https://sketchfab.com/annzep)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-bike-d9c4d3b44b2e4e4aa24e360c9830c0a1
Title: Retro  bike
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube98_phong1_0: THREE.Mesh
    pCube98_lambert3_0: THREE.Mesh
    pCube98_lambert2_0: THREE.Mesh
    pCube112_lambert7_0: THREE.Mesh
    pCube113_phong1_0: THREE.Mesh
    pCube113_lambert3_0: THREE.Mesh
    pCube113_lambert2_0: THREE.Mesh
    pCube114_phong1_0: THREE.Mesh
    pCube114_lambert3_0: THREE.Mesh
    pCube114_lambert2_0: THREE.Mesh
    pCube115_phong1_0: THREE.Mesh
    pCube115_lambert3_0: THREE.Mesh
    pCube115_lambert2_0: THREE.Mesh
    pCube116_phong1_0: THREE.Mesh
    pCube116_lambert3_0: THREE.Mesh
    pCube116_lambert2_0: THREE.Mesh
    pCube117_phong1_0: THREE.Mesh
    pCube117_lambert3_0: THREE.Mesh
    pCube117_lambert2_0: THREE.Mesh
    pCube118_phong1_0: THREE.Mesh
    pCube118_lambert3_0: THREE.Mesh
    pCube118_lambert2_0: THREE.Mesh
    pCube119_phong1_0: THREE.Mesh
    pCube119_lambert3_0: THREE.Mesh
    pCube119_lambert2_0: THREE.Mesh
    pCube120_phong1_0: THREE.Mesh
    pCube120_lambert3_0: THREE.Mesh
    pCube120_lambert2_0: THREE.Mesh
    pCube121_phong1_0: THREE.Mesh
    pCube121_lambert3_0: THREE.Mesh
    pCube121_lambert2_0: THREE.Mesh
    pCube122_phong1_0: THREE.Mesh
    pCube122_lambert3_0: THREE.Mesh
    pCube122_lambert2_0: THREE.Mesh
    pCube123_phong1_0: THREE.Mesh
    pCube123_lambert3_0: THREE.Mesh
    pCube123_lambert2_0: THREE.Mesh
    pCube124_phong1_0: THREE.Mesh
    pCube124_lambert3_0: THREE.Mesh
    pCube124_lambert2_0: THREE.Mesh
    pCube125_phong1_0: THREE.Mesh
    pCube125_lambert3_0: THREE.Mesh
    pCube125_lambert2_0: THREE.Mesh
    pCube126_phong1_0: THREE.Mesh
    pCube126_lambert3_0: THREE.Mesh
    pCube126_lambert2_0: THREE.Mesh
    pCube127_phong1_0: THREE.Mesh
    pCube127_lambert3_0: THREE.Mesh
    pCube127_lambert2_0: THREE.Mesh
    pCube128_phong1_0: THREE.Mesh
    pCube128_lambert3_0: THREE.Mesh
    pCube128_lambert2_0: THREE.Mesh
    pCube129_phong1_0: THREE.Mesh
    pCube129_lambert3_0: THREE.Mesh
    pCube129_lambert2_0: THREE.Mesh
    pCube131_phong1_0: THREE.Mesh
    pCube131_lambert3_0: THREE.Mesh
    pCube131_lambert2_0: THREE.Mesh
    pCube132_phong1_0: THREE.Mesh
    pCube132_lambert3_0: THREE.Mesh
    pCube132_lambert2_0: THREE.Mesh
    pCube133_phong1_0: THREE.Mesh
    pCube133_lambert3_0: THREE.Mesh
    pCube133_lambert2_0: THREE.Mesh
    pCube134_phong1_0: THREE.Mesh
    pCube134_lambert3_0: THREE.Mesh
    pCube134_lambert2_0: THREE.Mesh
    pCube135_phong1_0: THREE.Mesh
    pCube135_lambert3_0: THREE.Mesh
    pCube135_lambert2_0: THREE.Mesh
    pCube136_phong1_0: THREE.Mesh
    pCube136_lambert3_0: THREE.Mesh
    pCube136_lambert2_0: THREE.Mesh
    pCube138_phong1_0: THREE.Mesh
    pCube138_lambert3_0: THREE.Mesh
    pCube138_lambert2_0: THREE.Mesh
    pCube139_phong1_0: THREE.Mesh
    pCube139_lambert3_0: THREE.Mesh
    pCube139_lambert2_0: THREE.Mesh
    pCube140_phong1_0: THREE.Mesh
    pCube140_lambert3_0: THREE.Mesh
    pCube140_lambert2_0: THREE.Mesh
    pCube141_phong1_0: THREE.Mesh
    pCube141_lambert3_0: THREE.Mesh
    pCube141_lambert2_0: THREE.Mesh
    pCube142_phong1_0: THREE.Mesh
    pCube142_lambert3_0: THREE.Mesh
    pCube142_lambert2_0: THREE.Mesh
    pCube143_phong1_0: THREE.Mesh
    pCube143_lambert3_0: THREE.Mesh
    pCube143_lambert2_0: THREE.Mesh
    pCube144_phong1_0: THREE.Mesh
    pCube144_lambert3_0: THREE.Mesh
    pCube144_lambert2_0: THREE.Mesh
    pCube145_phong1_0: THREE.Mesh
    pCube145_lambert3_0: THREE.Mesh
    pCube145_lambert2_0: THREE.Mesh
    pCube146_phong1_0: THREE.Mesh
    pCube146_lambert3_0: THREE.Mesh
    pCube146_lambert2_0: THREE.Mesh
    pCube147_phong1_0: THREE.Mesh
    pCube147_lambert3_0: THREE.Mesh
    pCube147_lambert2_0: THREE.Mesh
    pCube148_phong1_0: THREE.Mesh
    pCube148_lambert3_0: THREE.Mesh
    pCube148_lambert2_0: THREE.Mesh
    pCube149_phong1_0: THREE.Mesh
    pCube149_lambert3_0: THREE.Mesh
    pCube149_lambert2_0: THREE.Mesh
    pCube150_phong1_0: THREE.Mesh
    pCube150_lambert3_0: THREE.Mesh
    pCube150_lambert2_0: THREE.Mesh
    pCube151_phong1_0: THREE.Mesh
    pCube151_lambert3_0: THREE.Mesh
    pCube151_lambert2_0: THREE.Mesh
    pCube152_phong1_0: THREE.Mesh
    pCube152_lambert3_0: THREE.Mesh
    pCube152_lambert2_0: THREE.Mesh
    pCube153_phong1_0: THREE.Mesh
    pCube153_lambert3_0: THREE.Mesh
    pCube153_lambert2_0: THREE.Mesh
    pCube155_phong1_0: THREE.Mesh
    pCube155_lambert3_0: THREE.Mesh
    pCube155_lambert2_0: THREE.Mesh
    pCube156_phong1_0: THREE.Mesh
    pCube156_lambert3_0: THREE.Mesh
    pCube156_lambert2_0: THREE.Mesh
    pCube157_phong1_0: THREE.Mesh
    pCube157_lambert3_0: THREE.Mesh
    pCube157_lambert2_0: THREE.Mesh
    pCube158_phong1_0: THREE.Mesh
    pCube158_lambert3_0: THREE.Mesh
    pCube158_lambert2_0: THREE.Mesh
    pCube160_phong1_0: THREE.Mesh
    pCube160_lambert3_0: THREE.Mesh
    pCube160_lambert2_0: THREE.Mesh
    pCube161_phong1_0: THREE.Mesh
    pCube161_lambert3_0: THREE.Mesh
    pCube161_lambert2_0: THREE.Mesh
    pCube162_phong1_0: THREE.Mesh
    pCube162_lambert3_0: THREE.Mesh
    pCube162_lambert2_0: THREE.Mesh
    pCube163_phong1_0: THREE.Mesh
    pCube163_lambert3_0: THREE.Mesh
    pCube163_lambert2_0: THREE.Mesh
    pCube164_phong1_0: THREE.Mesh
    pCube164_lambert3_0: THREE.Mesh
    pCube164_lambert2_0: THREE.Mesh
    pCube165_phong1_0: THREE.Mesh
    pCube165_lambert3_0: THREE.Mesh
    pCube165_lambert2_0: THREE.Mesh
    pCube166_phong1_0: THREE.Mesh
    pCube166_lambert3_0: THREE.Mesh
    pCube166_lambert2_0: THREE.Mesh
    pCube167_phong1_0: THREE.Mesh
    pCube167_lambert3_0: THREE.Mesh
    pCube167_lambert2_0: THREE.Mesh
    pCube168_phong1_0: THREE.Mesh
    pCube168_lambert3_0: THREE.Mesh
    pCube168_lambert2_0: THREE.Mesh
    pCube169_phong1_0: THREE.Mesh
    pCube169_lambert3_0: THREE.Mesh
    pCube169_lambert2_0: THREE.Mesh
    pCube170_phong1_0: THREE.Mesh
    pCube170_lambert3_0: THREE.Mesh
    pCube170_lambert2_0: THREE.Mesh
    pCube171_phong1_0: THREE.Mesh
    pCube171_lambert3_0: THREE.Mesh
    pCube171_lambert2_0: THREE.Mesh
    pCube172_phong1_0: THREE.Mesh
    pCube172_lambert3_0: THREE.Mesh
    pCube172_lambert2_0: THREE.Mesh
    pCube173_phong1_0: THREE.Mesh
    pCube173_lambert3_0: THREE.Mesh
    pCube173_lambert2_0: THREE.Mesh
    pCube174_phong1_0: THREE.Mesh
    pCube174_lambert3_0: THREE.Mesh
    pCube174_lambert2_0: THREE.Mesh
    pCube175_phong1_0: THREE.Mesh
    pCube175_lambert3_0: THREE.Mesh
    pCube175_lambert2_0: THREE.Mesh
    pCube176_phong1_0: THREE.Mesh
    pCube176_lambert3_0: THREE.Mesh
    pCube176_lambert2_0: THREE.Mesh
    pCube177_phong1_0: THREE.Mesh
    pCube177_lambert3_0: THREE.Mesh
    pCube177_lambert2_0: THREE.Mesh
    pCube178_phong1_0: THREE.Mesh
    pCube178_lambert3_0: THREE.Mesh
    pCube178_lambert2_0: THREE.Mesh
    pCube179_phong1_0: THREE.Mesh
    pCube179_lambert3_0: THREE.Mesh
    pCube179_lambert2_0: THREE.Mesh
    pCube180_phong1_0: THREE.Mesh
    pCube180_lambert3_0: THREE.Mesh
    pCube180_lambert2_0: THREE.Mesh
    pCube181_phong1_0: THREE.Mesh
    pCube181_lambert3_0: THREE.Mesh
    pCube181_lambert2_0: THREE.Mesh
    pCube182_phong1_0: THREE.Mesh
    pCube182_lambert3_0: THREE.Mesh
    pCube182_lambert2_0: THREE.Mesh
    pCube183_phong1_0: THREE.Mesh
    pCube183_lambert3_0: THREE.Mesh
    pCube183_lambert2_0: THREE.Mesh
    pCube184_phong1_0: THREE.Mesh
    pCube184_lambert3_0: THREE.Mesh
    pCube184_lambert2_0: THREE.Mesh
    pCube185_phong1_0: THREE.Mesh
    pCube185_lambert3_0: THREE.Mesh
    pCube185_lambert2_0: THREE.Mesh
    pCube186_phong1_0: THREE.Mesh
    pCube186_lambert3_0: THREE.Mesh
    pCube186_lambert2_0: THREE.Mesh
    pCylinder56_phong5_0: THREE.Mesh
    polySurface1543_phong7_0: THREE.Mesh
    polySurface1542_lambert9_0: THREE.Mesh
    polySurface1544_lambert9_0: THREE.Mesh
    polySurface1545_lambert9_0: THREE.Mesh
    polySurface1539_phong5_0: THREE.Mesh
    pCube110_phong1_0: THREE.Mesh
    pCube110_lambert3_0: THREE.Mesh
    pCube110_lambert2_0: THREE.Mesh
    pCube110_lambert4_0: THREE.Mesh
    polySurface1537_lambert8_0: THREE.Mesh
    polySurface811_phong4_0: THREE.Mesh
    polySurface1322_phong8_0: THREE.Mesh
    polySurface1355_phong7_0: THREE.Mesh
    polySurface1368_lambert9_0: THREE.Mesh
    polySurface1512_lambert5_0: THREE.Mesh
    polySurface841_lambert1_0: THREE.Mesh
    polySurface1348_lambert6_0: THREE.Mesh
    polySurface1533_lambert10_0: THREE.Mesh
    polySurface1311_phong7_0: THREE.Mesh
    polySurface1354_phong7_0: THREE.Mesh
    polySurface1553_phong5_0: THREE.Mesh
    polySurface1546_lambert9_0: THREE.Mesh
    polySurface1558_phong7_0: THREE.Mesh
    polySurface1556_phong7_0: THREE.Mesh
    polySurface1350_phong5_0: THREE.Mesh
    polySurface1349_phong5_0: THREE.Mesh
    polySurface1345_phong5_0: THREE.Mesh
    polySurface1554_phong7_0: THREE.Mesh
    pCube187_phong1_0: THREE.Mesh
    polySurface547_lambert9_0: THREE.Mesh
    pCube66_phong5_0: THREE.Mesh
    polySurface1356_phong4_0: THREE.Mesh
    polySurface1548_phong6_0: THREE.Mesh
    polySurface1551_lambert9_0: THREE.Mesh
    polySurface1549_lambert9_0: THREE.Mesh
    polySurface812_phong4_0: THREE.Mesh
    pCube64_phong5_0: THREE.Mesh
    polySurface845_lambert1_0: THREE.Mesh
    polySurface870_lambert1_0: THREE.Mesh
    polySurface1370_phong5_0: THREE.Mesh
    polySurface843_phong3_0: THREE.Mesh
    polySurface1315_phong4_0: THREE.Mesh
    polySurface1136_phong7_0: THREE.Mesh
    polySurface1331_phong8_0: THREE.Mesh
    polySurface810_phong4_0: THREE.Mesh
    polySurface1342_phong5_0: THREE.Mesh
    polySurface1338_phong8_0: THREE.Mesh
    polySurface1321_phong8_0: THREE.Mesh
    polySurface1323_phong8_0: THREE.Mesh
    polySurface1341_phong4_0: THREE.Mesh
    polySurface1369_phong5_0: THREE.Mesh
    polySurface1324_phong8_0: THREE.Mesh
    polySurface1325_phong8_0: THREE.Mesh
    polySurface1327_phong8_0: THREE.Mesh
    polySurface1330_phong8_0: THREE.Mesh
    polySurface813_phong8_0: THREE.Mesh
    polySurface1326_phong8_0: THREE.Mesh
    polySurface1125_phong5_0: THREE.Mesh
    polySurface1175_phong7_0: THREE.Mesh
    polySurface1357_phong8_0: THREE.Mesh
    polySurface828_phong5_0: THREE.Mesh
    pCylinder52_phong5_0: THREE.Mesh
    pCylinder51_phong4_0: THREE.Mesh
    polySurface1340_phong8_0: THREE.Mesh
    polySurface1335_phong8_0: THREE.Mesh
    polySurface827_phong4_0: THREE.Mesh
    polySurface1534_lambert8_0: THREE.Mesh
    polySurface1536_phong5_0: THREE.Mesh
    polySurface1353_lambert6_0: THREE.Mesh
    polySurface1352_phong5_0: THREE.Mesh
    polySurface1318_phong8_0: THREE.Mesh
    polySurface1319_phong8_0: THREE.Mesh
    polySurface1550_lambert9_0: THREE.Mesh
    polySurface1317_phong8_0: THREE.Mesh
    polySurface1118_lambert5_0: THREE.Mesh
    polySurface1190_phong7_0: THREE.Mesh
    pCube65_phong5_0: THREE.Mesh
    pCube189_phong1_0: THREE.Mesh
    polySurface1540_phong4_0: THREE.Mesh
    polySurface1541_lambert9_0: THREE.Mesh
    polySurface1535_lambert9_0: THREE.Mesh
    polySurface1547_lambert9_0: THREE.Mesh
    polySurface1122_phong7_0: THREE.Mesh
    polySurface1346_phong7_0: THREE.Mesh
    polySurface1351_phong5_0: THREE.Mesh
    polySurface1119_phong5_0: THREE.Mesh
    polySurface1120_phong7_0: THREE.Mesh
    polySurface1557_phong5_0: THREE.Mesh
    polySurface546_phong4_0: THREE.Mesh
    polySurface556_phong7_0: THREE.Mesh
    polySurface555_phong7_0: THREE.Mesh
    pCube111_phong1_0: THREE.Mesh
    pCube111_lambert3_0: THREE.Mesh
    pCube111_lambert2_0: THREE.Mesh
    pCube111_lambert4_0: THREE.Mesh
    polySurface1344_phong5_0: THREE.Mesh
    polySurface1127_phong7_0: THREE.Mesh
    polySurface1552_phong7_0: THREE.Mesh
    polySurface1328_phong8_0: THREE.Mesh
    polySurface1188_phong8_0: THREE.Mesh
    polySurface1359_phong5_0: THREE.Mesh
    pCube154_phong1_0: THREE.Mesh
    pCube154_lambert3_0: THREE.Mesh
    pCube154_lambert2_0: THREE.Mesh
    pCube159_phong1_0: THREE.Mesh
    pCube159_lambert3_0: THREE.Mesh
    pCube159_lambert2_0: THREE.Mesh
    polySurface1334_phong8_0: THREE.Mesh
    polySurface1336_phong8_0: THREE.Mesh
    polySurface1332_phong8_0: THREE.Mesh
    polySurface1333_phong8_0: THREE.Mesh
    polySurface1343_phong2_0: THREE.Mesh
    polySurface1320_phong8_0: THREE.Mesh
    polySurface1329_phong8_0: THREE.Mesh
    pCube55_lambert6_0: THREE.Mesh
    polySurface1312_phong5_0: THREE.Mesh
    polySurface540_phong3_0: THREE.Mesh
    polySurface538_lambert1_0: THREE.Mesh
    pHelix2_phong7_0: THREE.Mesh
    polySurface1361_phong5_0: THREE.Mesh
    pCube191_phong1_0: THREE.Mesh
    pCube194_phong1_0: THREE.Mesh
    pCube190_phong1_0: THREE.Mesh
    pCube109_phong1_0: THREE.Mesh
    pCube109_lambert3_0: THREE.Mesh
    pCube109_lambert2_0: THREE.Mesh
    pCube109_lambert4_0: THREE.Mesh
    polySurface1339_phong8_0: THREE.Mesh
    polySurface1371_phong5_0: THREE.Mesh
    pHelix1_phong7_0: THREE.Mesh
    polySurface1538_lambert9_0: THREE.Mesh
    polySurface1337_phong8_0: THREE.Mesh
    pCube192_phong1_0: THREE.Mesh
    pCube188_phong1_0: THREE.Mesh
    polySurface665_phong2_0: THREE.Mesh
    pCube193_phong1_0: THREE.Mesh
    polySurface1555_phong5_0: THREE.Mesh
    pCube63_lambert10_0: THREE.Mesh
    polySurface1559_phong5_0: THREE.Mesh
    pCube195_phong1_0: THREE.Mesh
    pCube195_lambert3_0: THREE.Mesh
    pCube195_lambert2_0: THREE.Mesh
    pCube196_phong1_0: THREE.Mesh
    pCube196_lambert3_0: THREE.Mesh
    pCube196_lambert2_0: THREE.Mesh
    pCube197_phong1_0: THREE.Mesh
    pCube197_lambert3_0: THREE.Mesh
    pCube197_lambert2_0: THREE.Mesh
    pCube198_phong1_0: THREE.Mesh
    pCube198_lambert3_0: THREE.Mesh
    pCube198_lambert2_0: THREE.Mesh
    pCube199_phong1_0: THREE.Mesh
    pCube199_lambert3_0: THREE.Mesh
    pCube199_lambert2_0: THREE.Mesh
    pCube200_phong1_0: THREE.Mesh
    pCube200_lambert3_0: THREE.Mesh
    pCube200_lambert2_0: THREE.Mesh
    pCube201_phong1_0: THREE.Mesh
    pCube201_lambert3_0: THREE.Mesh
    pCube201_lambert2_0: THREE.Mesh
    pCube202_phong1_0: THREE.Mesh
    pCube202_lambert3_0: THREE.Mesh
    pCube202_lambert2_0: THREE.Mesh
    pCube203_phong1_0: THREE.Mesh
    pCube203_lambert3_0: THREE.Mesh
    pCube203_lambert2_0: THREE.Mesh
    pCube204_phong1_0: THREE.Mesh
    pCube204_lambert3_0: THREE.Mesh
    pCube204_lambert2_0: THREE.Mesh
    pCube205_phong1_0: THREE.Mesh
    pCube205_lambert3_0: THREE.Mesh
    pCube205_lambert2_0: THREE.Mesh
    pCube206_phong1_0: THREE.Mesh
    pCube206_lambert3_0: THREE.Mesh
    pCube206_lambert2_0: THREE.Mesh
    pCube207_phong1_0: THREE.Mesh
    pCube207_lambert3_0: THREE.Mesh
    pCube207_lambert2_0: THREE.Mesh
    pCube208_phong1_0: THREE.Mesh
    pCube208_lambert3_0: THREE.Mesh
    pCube208_lambert2_0: THREE.Mesh
    pCube209_phong1_0: THREE.Mesh
    pCube209_lambert3_0: THREE.Mesh
    pCube209_lambert2_0: THREE.Mesh
    pCube210_phong1_0: THREE.Mesh
    pCube210_lambert3_0: THREE.Mesh
    pCube210_lambert2_0: THREE.Mesh
    pCube211_phong1_0: THREE.Mesh
    pCube211_lambert3_0: THREE.Mesh
    pCube211_lambert2_0: THREE.Mesh
    pCube212_phong1_0: THREE.Mesh
    pCube212_lambert3_0: THREE.Mesh
    pCube212_lambert2_0: THREE.Mesh
    pCube213_phong1_0: THREE.Mesh
    pCube213_lambert3_0: THREE.Mesh
    pCube213_lambert2_0: THREE.Mesh
    pCube214_phong1_0: THREE.Mesh
    pCube214_lambert3_0: THREE.Mesh
    pCube214_lambert2_0: THREE.Mesh
    pCube215_phong1_0: THREE.Mesh
    pCube215_lambert3_0: THREE.Mesh
    pCube215_lambert2_0: THREE.Mesh
  }
  materials: {
    phong1: THREE.MeshStandardMaterial
    lambert3: THREE.MeshStandardMaterial
    lambert2: THREE.MeshStandardMaterial
    lambert7: THREE.MeshStandardMaterial
    phong5: THREE.MeshStandardMaterial
    phong7: THREE.MeshStandardMaterial
    lambert9: THREE.MeshStandardMaterial
    lambert4: THREE.MeshStandardMaterial
    lambert8: THREE.MeshStandardMaterial
    phong4: THREE.MeshStandardMaterial
    phong8: THREE.MeshStandardMaterial
    lambert5: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    lambert6: THREE.MeshStandardMaterial
    lambert10: THREE.MeshStandardMaterial
    phong6: THREE.MeshStandardMaterial
    phong3: THREE.MeshStandardMaterial
    phong2: THREE.MeshStandardMaterial
  }
  //@ts-ignore
  animations: GLTFAction[]
}
  //@ts-ignore

export function Bike(props: JSX.IntrinsicElements['group']) {
    //@ts-ignore

  const { nodes, materials } = useGLTF('/retro__bike.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.65, 0.134, 0.149]} rotation={[-0.093, -0.063, 0.082]}>
        <mesh geometry={nodes.pCube98_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube98_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube98_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-1.04, -0.215, 0]}>
        <mesh geometry={nodes.pCube114_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube114_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube114_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[2.665, 0, 1.776]}>
        <mesh geometry={nodes.pCube115_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube115_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube115_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[5.011, -0.758, 7.074]} rotation={[0.337, -0.104, -0.041]}>
        <mesh geometry={nodes.pCube117_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube117_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube117_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-2.449, -1.731, -3.522]} rotation={[0.251, -0.242, -0.029]}>
        <mesh geometry={nodes.pCube119_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube119_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube119_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[3.12, 0, 6.015]}>
        <mesh geometry={nodes.pCube120_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube120_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube120_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-0.399, 0, -3.511]}>
        <mesh geometry={nodes.pCube121_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube121_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube121_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-5.423, 0, 3.172]}>
        <mesh geometry={nodes.pCube122_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube122_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube122_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[5.146, -1.226, 0.749]}>
        <mesh geometry={nodes.pCube123_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube123_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube123_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-4.545, 0, 4.115]}>
        <mesh geometry={nodes.pCube125_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube125_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube125_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[7.596, 0, -3.513]}>
        <mesh geometry={nodes.pCube126_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube126_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube126_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-0.198, 0, -0.07]}>
        <mesh geometry={nodes.pCube127_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube127_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube127_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[2.78, -3.6, 8.43]} rotation={[-0.24, -0.378, -0.086]}>
        <mesh geometry={nodes.pCube128_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube128_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube128_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.065, -0.339, 5.068]}>
        <mesh geometry={nodes.pCube129_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube129_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube129_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-4.167, -1.967, -3.748]}>
        <mesh geometry={nodes.pCube131_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube131_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube131_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-5.509, -1.209, 1.748]}>
        <mesh geometry={nodes.pCube132_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube132_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube132_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[3.542, 0, 2.011]}>
        <mesh geometry={nodes.pCube133_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube133_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube133_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.784, 0, -0.678]}>
        <mesh geometry={nodes.pCube134_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube134_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube134_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-5.07, 0, 8.099]}>
        <mesh geometry={nodes.pCube135_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube135_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube135_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-1.024, -0.551, 1.261]} rotation={[-0.195, -0.172, 0.053]}>
        <mesh geometry={nodes.pCube136_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube136_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube136_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-3.085, 2.123, 3.61]}>
        <mesh geometry={nodes.pCube138_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube138_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube138_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0, -0.024, -1.74]} rotation={[-0.244, 0, 0]}>
        <mesh geometry={nodes.pCube139_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube139_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube139_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-2.131, -4.539, -3.584]} rotation={[0.086, -0.138, 0.201]}>
        <mesh geometry={nodes.pCube140_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube140_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube140_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[3.935, 8.448, -3.074]} rotation={[0.31, -0.333, -0.275]}>
        <mesh geometry={nodes.pCube141_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube141_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube141_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[3.124, 0.909, 0.341]}>
        <mesh geometry={nodes.pCube142_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube142_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube142_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0, 1.625, 0]}>
        <mesh geometry={nodes.pCube143_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube143_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube143_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0, 2.812, 0]}>
        <mesh geometry={nodes.pCube145_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube145_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube145_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[5.08, 0, -2.879]}>
        <mesh geometry={nodes.pCube146_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube146_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube146_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-5.158, 0, -0.557]}>
        <mesh geometry={nodes.pCube147_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube147_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube147_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-0.259, 0, 2.605]}>
        <mesh geometry={nodes.pCube150_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube150_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube150_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[2.973, 1.063, -11.762]} rotation={[0.159, -0.282, 0.13]}>
        <mesh geometry={nodes.pCube151_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube151_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube151_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-6.215, 2.677, 0.856]}>
        <mesh geometry={nodes.pCube152_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube152_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube152_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[6.071, 4.378, 8.955]} rotation={[0.212, -0.127, -0.062]}>
        <mesh geometry={nodes.pCube155_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube155_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube155_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0, -0.327, 0]}>
        <mesh geometry={nodes.pCube157_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube157_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube157_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-3.36, 0, 0.668]}>
        <mesh geometry={nodes.pCube158_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube158_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube158_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[28.07, 11.628, -1.173]} rotation={[0.463, -0.671, 0.233]}>
        <mesh geometry={nodes.pCube162_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube162_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube162_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[5.546, 2.878, -9.944]} rotation={[0.318, -0.285, 0.173]}>
        <mesh geometry={nodes.pCube166_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube166_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube166_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-0.725, 0, -0.889]}>
        <mesh geometry={nodes.pCube167_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube167_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube167_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0.898, 0, -5.459]}>
        <mesh geometry={nodes.pCube171_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube171_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube171_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[4.848, 4.919, -1.486]} rotation={[0.226, -0.041, -0.246]}>
        <mesh geometry={nodes.pCube172_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube172_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube172_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[4.908, 0, 6.42]}>
        <mesh geometry={nodes.pCube173_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube173_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube173_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-2.379, -3.243, -1.592]} rotation={[0.06, -0.114, 0.152]}>
        <mesh geometry={nodes.pCube176_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube176_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube176_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0, -0.438, 0]}>
        <mesh geometry={nodes.pCube177_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube177_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube177_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0, -0.286, 0]}>
        <mesh geometry={nodes.pCube181_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube181_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube181_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.148, 2.434, -1.976]} rotation={[0.2, -0.132, -0.094]}>
        <mesh geometry={nodes.pCube183_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube183_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube183_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group rotation={[0, 0, 0.122]}>
        <mesh geometry={nodes.polySurface1543_phong7_0.geometry} material={materials.phong7} position={[-1.435, 0.35, -0.902]} rotation={[0.046, 0.27, -0.005]} />
        <mesh geometry={nodes.polySurface1542_lambert9_0.geometry} material={materials.lambert9} position={[-1.435, 0.35, -0.902]} rotation={[0.046, 0.27, -0.005]} />
        <mesh geometry={nodes.polySurface1544_lambert9_0.geometry} material={materials.lambert9} position={[-1.435, 0.35, -0.902]} rotation={[0.046, 0.27, -0.005]} />
        <mesh geometry={nodes.polySurface1545_lambert9_0.geometry} material={materials.lambert9} position={[-1.435, 0.35, -0.902]} rotation={[0.046, 0.27, -0.005]} />
      </group>
      <group position={[0, 0.169, 0]}>
        <group position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]}>
          <mesh geometry={nodes.pCube110_phong1_0.geometry} material={materials.phong1} />
          <mesh geometry={nodes.pCube110_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.pCube110_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCube110_lambert4_0.geometry} material={materials.lambert4} />
        </group>
        <group position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]}>
          <mesh geometry={nodes.pCube111_phong1_0.geometry} material={materials.phong1} />
          <mesh geometry={nodes.pCube111_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.pCube111_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCube111_lambert4_0.geometry} material={materials.lambert4} />
        </group>
        <group position={[0, 3.749, 1.76]} rotation={[0.192, 0, 0]}>
          <mesh geometry={nodes.pCube154_phong1_0.geometry} material={materials.phong1} />
          <mesh geometry={nodes.pCube154_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.pCube154_lambert2_0.geometry} material={materials.lambert2} />
        </group>
        <group position={[-7.969, -1.399, 5.836]}>
          <mesh geometry={nodes.pCube159_phong1_0.geometry} material={materials.phong1} />
          <mesh geometry={nodes.pCube159_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.pCube159_lambert2_0.geometry} material={materials.lambert2} />
        </group>
        <group position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]}>
          <mesh geometry={nodes.pCube109_phong1_0.geometry} material={materials.phong1} />
          <mesh geometry={nodes.pCube109_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.pCube109_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCube109_lambert4_0.geometry} material={materials.lambert4} />
        </group>
        <mesh geometry={nodes.polySurface1539_phong5_0.geometry} material={materials.phong5} position={[-1.018, -2.529, -0.575]} rotation={[-0.175, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1537_lambert8_0.geometry} material={materials.lambert8} position={[-1.018, -2.529, -0.575]} rotation={[-0.175, 0, 0.07]} />
        <mesh geometry={nodes.polySurface811_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1322_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1355_phong7_0.geometry} material={materials.phong7} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1368_lambert9_0.geometry} material={materials.lambert9} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1512_lambert5_0.geometry} material={materials.lambert5} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface841_lambert1_0.geometry} material={materials.lambert1} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1348_lambert6_0.geometry} material={materials.lambert6} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1533_lambert10_0.geometry} material={materials.lambert10} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1311_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1354_phong7_0.geometry} material={materials.phong7} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1553_phong5_0.geometry} material={materials.phong5} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1546_lambert9_0.geometry} material={materials.lambert9} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1558_phong7_0.geometry} material={materials.phong7} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1556_phong7_0.geometry} material={materials.phong7} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1350_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1349_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1345_phong5_0.geometry} material={materials.phong5} position={[-1.405, 0.144, -0.779]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1554_phong7_0.geometry} material={materials.phong7} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pCube187_phong1_0.geometry} material={materials.phong1} position={[-12.312, 22.446, -3.572]} rotation={[0.121, -0.247, -2.514]} />
        <mesh geometry={nodes.polySurface547_lambert9_0.geometry} material={materials.lambert9} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pCube66_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1356_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1548_phong6_0.geometry} material={materials.phong6} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1551_lambert9_0.geometry} material={materials.lambert9} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1549_lambert9_0.geometry} material={materials.lambert9} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface812_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCube64_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface845_lambert1_0.geometry} material={materials.lambert1} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface870_lambert1_0.geometry} material={materials.lambert1} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1370_phong5_0.geometry} material={materials.phong5} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface843_phong3_0.geometry} material={materials.phong3} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1315_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1136_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1331_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface810_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1342_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1338_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1321_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1323_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1341_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1369_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1324_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1325_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1327_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1330_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface813_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1326_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1125_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1175_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1357_phong8_0.geometry} material={materials.phong8} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface828_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCylinder52_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCylinder51_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1340_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1335_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface827_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1534_lambert8_0.geometry} material={materials.lambert8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1536_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1353_lambert6_0.geometry} material={materials.lambert6} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1352_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1318_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1319_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1550_lambert9_0.geometry} material={materials.lambert9} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1317_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1118_lambert5_0.geometry} material={materials.lambert5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1190_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCube65_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pCube189_phong1_0.geometry} material={materials.phong1} position={[1.474, 22.342, -7.071]} rotation={[2.928, -0.839, 0.199]} scale={0.857} />
        <mesh geometry={nodes.polySurface1540_phong4_0.geometry} material={materials.phong4} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1541_lambert9_0.geometry} material={materials.lambert9} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1535_lambert9_0.geometry} material={materials.lambert9} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1547_lambert9_0.geometry} material={materials.lambert9} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1122_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1346_phong7_0.geometry} material={materials.phong7} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1351_phong5_0.geometry} material={materials.phong5} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1119_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1120_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1557_phong5_0.geometry} material={materials.phong5} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface546_phong4_0.geometry} material={materials.phong4} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface556_phong7_0.geometry} material={materials.phong7} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface555_phong7_0.geometry} material={materials.phong7} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1344_phong5_0.geometry} material={materials.phong5} position={[-1.417, -1.262, -1.397]} rotation={[0.012, 0.274, 0.122]} scale={1.111} />
        <mesh geometry={nodes.polySurface1127_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1552_phong7_0.geometry} material={materials.phong7} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1328_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1188_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1359_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1334_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1336_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1332_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1333_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1343_phong2_0.geometry} material={materials.phong2} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1320_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1329_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCube55_lambert6_0.geometry} material={materials.lambert6} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1312_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface540_phong3_0.geometry} material={materials.phong3} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface538_lambert1_0.geometry} material={materials.lambert1} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pHelix2_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1361_phong5_0.geometry} material={materials.phong5} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCube191_phong1_0.geometry} material={materials.phong1} position={[-9.569, 22.002, 8.427]} rotation={[0.201, 0.946, -2.707]} />
        <mesh geometry={nodes.pCube194_phong1_0.geometry} material={materials.phong1} position={[-4.172, 21.78, -9.836]} rotation={[-0.006, -1.096, -2.662]} scale={0.857} />
        <mesh geometry={nodes.pCube190_phong1_0.geometry} material={materials.phong1} position={[-0.37, 22.356, 4.634]} rotation={[-2.897, 0.594, 0.146]} scale={0.857} />
        <mesh geometry={nodes.polySurface1339_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1371_phong5_0.geometry} material={materials.phong5} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pHelix1_phong7_0.geometry} material={materials.phong7} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1538_lambert9_0.geometry} material={materials.lambert9} position={[-1.018, -2.529, -0.575]} rotation={[-0.175, 0, 0.07]} />
        <mesh geometry={nodes.polySurface1337_phong8_0.geometry} material={materials.phong8} position={[-1.018, 0.061, -0.492]} rotation={[0, 0, 0.07]} />
        <mesh geometry={nodes.pCube192_phong1_0.geometry} material={materials.phong1} position={[-7.052, 21.364, -7.896]} rotation={[-0.006, -1.078, -2.662]} scale={0.857} />
        <mesh geometry={nodes.pCube188_phong1_0.geometry} material={materials.phong1} position={[-5.475, 22.491, 3.657]} rotation={[-0.708, 1.257, -2.173]} scale={0.857} />
        <mesh geometry={nodes.polySurface665_phong2_0.geometry} material={materials.phong2} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pCube193_phong1_0.geometry} material={materials.phong1} position={[4.182, 23.022, -0.834]} rotation={[-3.102, -0.186, 0.265]} scale={0.857} />
        <mesh geometry={nodes.polySurface1555_phong5_0.geometry} material={materials.phong5} position={[-1.469, 0.144, -0.758]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.pCube63_lambert10_0.geometry} material={materials.lambert10} position={[-1.467, 0.172, -0.902]} rotation={[0.012, 0.274, 0.122]} />
        <mesh geometry={nodes.polySurface1559_phong5_0.geometry} material={materials.phong5} position={[-1.987, -0.584, 11.144]} rotation={[0, 0, 0.07]} scale={[0.112, 0.397, 0.397]} />
      </group>
      <group position={[1.15, 2.257, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube195_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube195_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube195_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.15, 1.581, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube196_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube196_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube196_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.15, 0, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube197_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube197_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube197_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0.619, 0, 20.597]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube198_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube198_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube198_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-1.155, -1.136, 18.543]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube199_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube199_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube199_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-2.007, 0, 18.132]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube200_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube200_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube200_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-4.646, 3.48, 23.415]} rotation={[-3.101, 0.254, 2.952]}>
        <mesh geometry={nodes.pCube201_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube201_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube201_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-2.405, -0.505, 24.099]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube202_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube202_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube202_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[8.654, 0, 18.584]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube203_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube203_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube203_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.15, 0, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube204_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube204_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube204_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[17.483, 0, 0.314]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube205_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube205_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube205_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[8.879, 3.422, 22.891]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube206_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube206_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube206_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-7.178, -14.29, 29.091]} rotation={[3.019, 0.406, -2.58]}>
        <mesh geometry={nodes.pCube207_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube207_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube207_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.15, 0, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube208_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube208_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube208_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[2.662, 2.742, 21.27]} rotation={[3.122, 0.184, 3.072]}>
        <mesh geometry={nodes.pCube209_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube209_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube209_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.15, 1.307, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube210_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube210_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube210_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[0.833, -6.222, 17.476]} rotation={[-2.98, -0.044, -2.855]}>
        <mesh geometry={nodes.pCube211_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube211_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube211_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[1.15, 0, 21.949]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube212_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube212_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube212_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[3.522, -1.072, 20.911]} rotation={[-3.015, 0.094, 3.107]}>
        <mesh geometry={nodes.pCube213_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube213_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube213_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[4.965, 0, 14.101]} rotation={[-Math.PI, 0.122, -Math.PI]}>
        <mesh geometry={nodes.pCube214_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube214_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube214_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-19.679, 0, -8.976]}>
        <mesh geometry={nodes.pCube215_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.pCube215_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCube215_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <mesh geometry={nodes.pCube112_lambert7_0.geometry} material={materials.lambert7} />
      <mesh geometry={nodes.pCube113_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube113_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube113_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube116_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube116_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube116_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube118_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube118_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube118_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube124_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube124_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube124_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube144_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube144_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube144_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube148_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube148_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube148_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube149_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube149_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube149_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube153_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube153_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube153_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube156_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube156_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube156_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube160_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube160_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube160_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube161_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube161_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube161_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube163_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube163_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube163_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube164_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube164_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube164_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube165_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube165_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube165_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube168_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube168_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube168_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube169_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube169_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube169_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube170_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube170_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube170_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube174_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube174_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube174_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube175_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube175_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube175_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube178_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube178_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube178_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube179_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube179_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube179_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube180_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube180_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube180_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube182_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube182_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube182_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube184_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube184_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube184_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube185_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube185_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube185_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube186_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCube186_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube186_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCylinder56_phong5_0.geometry} material={materials.phong5} position={[-0.555, -0.799, 0.202]} rotation={[0, 0, -0.175]} />
    </group>
  )
}

useGLTF.preload('/retro__bike.glb')
