/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src\assets\models\ship.glb -t 
Author: danyelon (https://sketchfab.com/adelin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/capsule-corporation-spaceship-low-poly-free-3ca2d8ea5320441b83b25520756a89f6
Title: Capsule Corporation Spaceship - Low Poly - Free
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
  }
  materials: {
    Base_low: THREE.MeshStandardMaterial
    BrazosDoor_low: THREE.MeshStandardMaterial
    Floor_low: THREE.MeshStandardMaterial
    Ground_low: THREE.MeshStandardMaterial
    Interior_low: THREE.MeshStandardMaterial
    Marco_low: THREE.MeshStandardMaterial
    Marcoext_low: THREE.MeshStandardMaterial
    Pata_base_low: THREE.MeshStandardMaterial
    Patas_low: THREE.MeshStandardMaterial
    Windows: THREE.MeshStandardMaterial
    door_low: THREE.MeshStandardMaterial
    gravity_low: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export  function Ship(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('src/assets/models/ship.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Base_low} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BrazosDoor_low} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Floor_low} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Ground_low} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Interior_low} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Marco_low} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Marcoext_low} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Pata_base_low} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Patas_low} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.door_low} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.gravity_low} />
      </group>
    </group>
  )
}

useGLTF.preload('src/assets/models/ship.glb')
